// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cases.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addCase = `-- name: AddCase :one
INSERT INTO cases (
    id, 
    title, 
    description, 
    created_at, 
    updated_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, description, created_at, updated_at
`

type AddCaseParams struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) AddCase(ctx context.Context, arg AddCaseParams) (Case, error) {
	row := q.db.QueryRowContext(ctx, addCase,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCase = `-- name: DeleteCase :exec
DELETE FROM cases
WHERE id = $1
`

func (q *Queries) DeleteCase(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCase, id)
	return err
}

const getCaseByID = `-- name: GetCaseByID :one
SELECT id, title, description, created_at, updated_at 
FROM cases
WHERE id = $1 
LIMIT 1
`

func (q *Queries) GetCaseByID(ctx context.Context, id uuid.UUID) (Case, error) {
	row := q.db.QueryRowContext(ctx, getCaseByID, id)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCases = `-- name: ListCases :many
SELECT id, title, description, created_at, updated_at 
FROM cases
ORDER BY created_at DESC
`

func (q *Queries) ListCases(ctx context.Context) ([]Case, error) {
	rows, err := q.db.QueryContext(ctx, listCases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Case
	for rows.Next() {
		var i Case
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCaseDescription = `-- name: UpdateCaseDescription :exec
UPDATE cases
SET description = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateCaseDescriptionParams struct {
	ID          uuid.UUID `json:"id"`
	Description *string   `json:"description"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateCaseDescription(ctx context.Context, arg UpdateCaseDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateCaseDescription, arg.ID, arg.Description, arg.UpdatedAt)
	return err
}

const updateCaseTitle = `-- name: UpdateCaseTitle :exec
UPDATE cases
SET title = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateCaseTitleParams struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateCaseTitle(ctx context.Context, arg UpdateCaseTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateCaseTitle, arg.ID, arg.Title, arg.UpdatedAt)
	return err
}
