// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: milestones.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addMilestone = `-- name: AddMilestone :one
INSERT INTO milestones (
    id,
    case_id,
    title,
    description,
    event_date,
    created_at,
    updated_at
) 
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, case_id, title, description, event_date, created_at, updated_at
`

type AddMilestoneParams struct {
	ID          uuid.UUID `json:"id"`
	CaseID      uuid.UUID `json:"case_id"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	EventDate   time.Time `json:"event_date"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) AddMilestone(ctx context.Context, arg AddMilestoneParams) (Milestone, error) {
	row := q.db.QueryRowContext(ctx, addMilestone,
		arg.ID,
		arg.CaseID,
		arg.Title,
		arg.Description,
		arg.EventDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Title,
		&i.Description,
		&i.EventDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMilestone = `-- name: DeleteMilestone :exec
DELETE FROM milestones
WHERE id = $1
`

func (q *Queries) DeleteMilestone(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMilestone, id)
	return err
}

const getMilestoneByID = `-- name: GetMilestoneByID :one
SELECT id, title, description, created_at, updated_at 
FROM cases
WHERE id = $1 
LIMIT 1
`

func (q *Queries) GetMilestoneByID(ctx context.Context, id uuid.UUID) (Case, error) {
	row := q.db.QueryRowContext(ctx, getMilestoneByID, id)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMilestonesByCase = `-- name: ListMilestonesByCase :many
SELECT id, case_id, title, description, event_date, created_at, updated_at 
FROM milestones
WHERE case_id = $1
ORDER BY event_date ASC
`

func (q *Queries) ListMilestonesByCase(ctx context.Context, caseID uuid.UUID) ([]Milestone, error) {
	rows, err := q.db.QueryContext(ctx, listMilestonesByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Milestone
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.Title,
			&i.Description,
			&i.EventDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventDate = `-- name: UpdateEventDate :exec
UPDATE milestones
SET event_date = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateEventDateParams struct {
	ID        uuid.UUID `json:"id"`
	EventDate time.Time `json:"event_date"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateEventDate(ctx context.Context, arg UpdateEventDateParams) error {
	_, err := q.db.ExecContext(ctx, updateEventDate, arg.ID, arg.EventDate, arg.UpdatedAt)
	return err
}

const updateMilestoneDescription = `-- name: UpdateMilestoneDescription :exec
UPDATE milestones
SET description = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateMilestoneDescriptionParams struct {
	ID          uuid.UUID `json:"id"`
	Description *string   `json:"description"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateMilestoneDescription(ctx context.Context, arg UpdateMilestoneDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateMilestoneDescription, arg.ID, arg.Description, arg.UpdatedAt)
	return err
}

const updateMilestoneTitle = `-- name: UpdateMilestoneTitle :exec
UPDATE milestones
SET title = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateMilestoneTitleParams struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateMilestoneTitle(ctx context.Context, arg UpdateMilestoneTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateMilestoneTitle, arg.ID, arg.Title, arg.UpdatedAt)
	return err
}
