// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Case struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Milestone struct {
	ID          uuid.UUID `json:"id"`
	CaseID      uuid.UUID `json:"case_id"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	EventDate   time.Time `json:"event_date"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type User struct {
	ID             uuid.UUID `json:"id"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Video struct {
	ID                 uuid.UUID     `json:"id"`
	MilestoneID        uuid.NullUUID `json:"milestone_id"`
	YoutubeVideoID     string        `json:"youtube_video_id"`
	Title              string        `json:"title"`
	ChannelName        string        `json:"channel_name"`
	Description        *string       `json:"description"`
	Status             string        `json:"status"`
	Category           string        `json:"category"`
	AiSummary          *string       `json:"ai_summary"`
	RawTranscript      *string       `json:"raw_transcript"`
	EstimatedEventDate sql.NullTime  `json:"estimated_event_date"`
	EnrichedDate       sql.NullTime  `json:"enriched_date"`
	SummarySource      string        `json:"summary_source"`
	PublishedAt        time.Time     `json:"published_at"`
	CreatedAt          time.Time     `json:"created_at"`
	UpdatedAt          time.Time     `json:"updated_at"`
}
